{
 "title": "Observability – Application Monitoring",
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "label_values(probe_success, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Website Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{project=~\"$project\",service='website'}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "probe_duration_seconds{project=~\"$project\"}"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\"}"
    }
   ]
  }
 ]
}