{
 "title": "Observability – NOC Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "label_values(probe_success, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Services UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(probe_success)" }
   ]
  },
  {
   "title": "Services DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(probe_success)-sum(probe_success)"
    }
   ]
  },
  {
   "title": "Website SLA 24h %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{service='website'}[24h])*100"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, probe_duration_seconds[5m])"
    }
   ]
  }
 ]
}